version: '2'
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: ./Dockerfile
      network: host
    ports:
      - "8081:80"
  backend:
    build:
      context: ./back-end
      dockerfile: ./Dockerfile
      network: host
