// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'nav-icon-list': string;
  'nav-logo': string;
  'navigation': string;
}
export const cssExports: CssExports;
export default cssExports;
